{{- if .Values.qdrant.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kovanica-agent.fullname" . }}-qdrant
  labels:
    {{- include "kovanica-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
spec:
  replicas: {{ .Values.qdrant.replicaCount }}
  selector:
    matchLabels:
      {{- include "kovanica-agent.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: qdrant
  template:
    metadata:
      labels:
        {{- include "kovanica-agent.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: qdrant
    spec:
      containers:
        - name: qdrant
          image: "{{ .Values.qdrant.image.repository }}:{{ .Values.qdrant.image.tag }}"
          imagePullPolicy: {{ .Values.qdrant.image.pullPolicy }}
          ports:
            - containerPort: 6333
          resources:
{{ toYaml .Values.qdrant.resources | indent 12 }}
          volumeMounts:
            - name: qdrant-storage
              mountPath: /qdrant/storage
      volumes:
        - name: qdrant-storage
          {{- if .Values.qdrant.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.qdrant.persistence.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
{{- end }}
