{{- if not .Values.agent.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kovanica-agent.fullname" . }}-secret
  labels:
    {{- include "kovanica-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  openai-api-key: "{{ .Values.agent.secretData.openai-api-key }}"
  dev-token: "{{ .Values.agent.secretData.dev-token }}"
{{- end }}
