apiVersion: v1
kind: Service
metadata:
  name: {{ include "kovanica-agent.fullname" . }}-agent
  labels:
    {{- include "kovanica-agent.labels" . | nindent 4 }}
    app.kubernetes.io/component: agent
spec:
  type: {{ .Values.agent.service.type }}
  ports:
    - port: {{ .Values.agent.service.port }}
      targetPort: {{ .Values.agent.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "kovanica-agent.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: agent
